### ISSUE TITLE
Two test cases seem to fail environment-dependently for no discernible reason

### ISSUE THREAD

**Issue by antecedent** [antecedent/patchwork#112]
- `call-original.phpt`
 - `multiple-patches.phpt`

These have been failing ever since the migration to GH Actions.

What is strange is that locally, I can run the entire suite with all passes. @jrfnl has noted the same result.

I am running PHP 8.0.9 NTS VC++19 x64, Windows 10, and PHPUnit 9.5.8. Aside from the Windows, everything seems to match up with what GitHub is running for PHP 8.0.

**Comment by jrfnl** [comment]
@antecedent I think I've figured it out. Hang on...

**Comment by jrfnl** [comment]
Yup. It's to do with an ini setting on GH Actions, not with the actual code or the tests themselves. PR #113 fixes the above, but exposes that another test is actually failing `language-constructs.phpt`:

```
--- Expected
+++ Actual
@@ @@
-'===DONE==='
+'Warning: assert(): assert($calls['die'] == [[], [], []]) failed in path/to/Temp/PHP13C3.tmp on line 34\n
+\n
+Warning: assert(): assert($calls['echo'] == [['This is a string'], ['This is a string', ' and this is another one'], ['Hello ', 'world']]) failed in path/to/Temp/PHP13C3.tmp on line 44\n
+===DONE==='

path/to/tests/language-constructs.phpt:66
```

I can reproduce that failure locally (on Windows as well) and consistently against all supported PHP versions.

**Comment by jrfnl** [comment]
@antecedent Looks like some of the other changes you made earlier today actually already fixed the above mentioned new failure and all I needed to do was to pull in the latest changes from `master`.

I've re-run the tests locally against all supported PHP versions (PHP 5.4 - 81) again and all now pass.
