### ISSUE TITLE
Add support for reserved words used as method names

### ISSUE THREAD

**Issue by pkopi** [antecedent/patchwork#120]
Prior to PHP 7, reserved keywords can be used as class method names.

When using patchwork for unit tests(using phpunit and symfony) following error occured:

`During class fetch: Uncaught ParseError: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in vendor/symfony/dependency-injection/Loader/Configurator/Traits/ClassTrait.php:26`

Temporary workaround for this issue is to load ClassTrait before the patchwork library is loaded, but I would appreciate if support for reserved keywords as method names will be added to the library. Thank you!

**Comment by jrfnl** [comment]
Related to #104

**Comment by antecedent** [comment]
Thank you for the report, @pkopi! And apologies for the delay. It was quite a surprise to me that `token_get_all()` has a flag, `TOKEN_PARSE`, that should solve all of this. It even had it for quite a while already. I will try switching it on.
