### ISSUE TITLE
missing phar releases

### ISSUE THREAD

**Issue by DanielRuf** [antecedent/patchwork#122]
The website https://patchwork2.org/ still links to 2.1.15 but for the releases after this there are no phar files.

**Comment by jrfnl** [comment]
@DanielRuf Thanks for pointing that out.

@antecedent I can't find any information on how the Phar file was generated up to now. Want to share your process ?

If you like, I'd be happy to create some adjustments to existing and/or add new GH Actions workflows to automate this.

Things I'm thinking about:
* Set things up to be able to build the Phar file with [Box](https://github.com/box-project/box/) and build it on each PR. The Phar would then automatically be available as a build artifact for each PR.
* Include a test in the test workflow which would use the Phar so the Phar is also tested automatically on each PR.
* Create a draft release whenever a tag is pushed and automatically generate the Phar file and attach it to it.

Also, once that's set up, I could make some tweaks to the GH Pages website setup to:
* Use the GH API to retrieve the version number for the last release.
* Use the GH API to retrieve the changelogs.
* Add a trigger in the release workflow to push an empty commit to the GH Pages website when a tag is pushed, so the website gets regenerated (which would make it automatically update).

What do you think ?

**Comment by jrfnl** [comment]
@antecedent If you need some inspiration for the above suggestions:
* Example configuration for [Box](https://github.com/box-project/box/): https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/box.json
    Note: this config is set-up to not run into PHP cross-version issues as Box still has some issues depending on which features are used (PHP_Scoper and the requirements checker are not fully compatible with PHP 8.1 yet).
* Example workflow which creates the Phar and uploads it as an artifact as part of the regular CI/test workflow: https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/.github/workflows/test.yml#L43-L79 and https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/.github/workflows/test.yml#L138-L143
* Release workflow which uploads the Phar to a draft release when a tag is pushed: https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/.github/workflows/release.yml

**Comment by jrfnl** [comment]
@antecedent Nice work on the Release workflow! Want me to give you a hand on the GH pages part ? (or talk you through it ?)

**Comment by jrfnl** [comment]
@antecedent Hint for what you are struggling with now: you need to use `actions/checkout` to checkout the `gh-pages` branch of the repo before attempting to commit to it.

(though there are some more tweaks you probably want to make, like only push after the release is published and tweaks to the GH Pages site setup to use the GH API so it will automatically update)

**Comment by antecedent** [comment]
Thank you! I will try this right now.

**Comment by jrfnl** [comment]
@antecedent Getting there, but looks like you removed a little too much. Want me to jump on a call with you ?

**Comment by antecedent** [comment]
Okay, it will be easier this way. Thanks for offering help :) I want to take a little break now, though. Could we have a call at 11:50 UTC?

**Comment by jrfnl** [comment]
Yeah, that should be fine. We can use whereby.com/jrfnl if you like.

**Comment by jrfnl** [comment]
Little delay expected here, Can we make it 12:15 UTC ?

**Comment by antecedent** [comment]
Sure, 12:15 it is.

**Comment by jrfnl** [comment]
Thanks. Delay is resolved, so whenever you are ready.

**Comment by DanielRuf** [comment]
Now I see a link to https://github.com/antecedent/patchwork/releases/download/2.1.21/patchwork.phar at the website. So I guess this is resolved. Closing.

Thank you very much!
