### ISSUE TITLE
Issues of version 2.1.18 with annotations @runInSeparateProcess and @preserveGlobalState

### ISSUE THREAD

**Issue by lloc** [antecedent/patchwork#123]
I had problems getting these tests passing: https://github.com/lloc/Multisite-Language-Switcher/blob/master/tests/test-mslstaxonomy.php

The error message wasn't so helpful:

```syntax error, unexpected 'and' (T_LOGICAL_AND), expecting end of file```

I was able to track it down to these annotations:

```
/**
 * @runInSeparateProcess
 * @preserveGlobalState disabled
 */
```
Downgrading to 2.1.17 solved the issue.

**Comment by jrfnl** [comment]
I have a feeling this is the same issue as #124. Are you by chance running the tests with code coverage turned on ?

**Comment by jrfnl** [comment]
@lloc Could you please re-run the tests with the latest [Patchwork release 2.1.19](https://github.com/antecedent/patchwork/releases/tag/2.1.19) ?

Would be great if we could confirm that the patch fixes your issue too (and to close this issue).
