### ISSUE TITLE
Patchwork 2.1.18 breaks `parse_ini_file()`

### ISSUE THREAD

**Issue by anomiex** [antecedent/patchwork#124]
After the release of Patchwork 2.1.18, we found strange errors in our CI when running PHPUnit with pcov. This turns out to be due to 84272b1ef2, and PHPUnit calling `parse_ini_file()` when run with pcov.

Grepping through PHP sources, I don't see anything other than `parse_ini_file()` that will incorrectly have `STREAM_OPEN_FOR_INCLUDE` set.

### Test case:

Use Debian's stock `/etc/php/8.0/cli/php.ini`, or create a `php.ini` with this excerpt from that file.
```ini
[PHP]

; This directive determines whether or not PHP will recognize code between
; <? and ?> tags as PHP source which should be processed as such. It is
; generally recommended that <?php and ?> should be used and that this feature
; should be disabled, as enabling it may result in issues when generating XML
; documents, however this remains supported for backward compatibility reasons.
; Note that this directive does not control the <?= shorthand tag, which can be
; used regardless of this directive.
; Default Value: On
; Development Value: Off
; Production Value: Off
; http://php.net/short-open-tag
short_open_tag = Off
```

Then test with
```php
<?php

// Adjust path as needed, of course.
parse_ini_file( '/etc/php/8.0/cli/php.ini' );

echo "ok\n";
```

### Expected output:

```
ok
```

### Actual output:

```
PHP Parse error:  syntax error, unexpected token "and", expecting end of file in  on line 5
```
The error is slightly more helpful in PHP 7.0 to 7.2:
```
PHP Warning:  parse_ini_file(/etc/php/8.0/cli/php.ini): failed to open stream: "Patchwork\CodeManipulation\Stream::stream_open" call failed in /path/to/test.php on line 4
PHP Parse error:  syntax error, unexpected 'and' (T_LOGICAL_AND), expecting end of file in  on line 189
```

**Comment by jrfnl** [comment]
FYI: I've just ran the BrainMonkey test suite and can see the same thing happening when using Xdebug for code coverage instead of `pcov`.

I'll run a test with the PR branch in a moment and will report back.

**Comment by jrfnl** [comment]
PR branch builds run and the tests for BrainMonkey pass 🟢 .

For reference:
* Failing build using Patchwork 2.1.18: https://github.com/Brain-WP/BrainMonkey/runs/4873944700?check_suite_focus=true
* Passing build using the PR branch from PR #125: https://github.com/Brain-WP/BrainMonkey/runs/4874227459?check_suite_focus=true

**Comment by jrfnl** [comment]
P.S.: nice detective work @anomiex !

**Comment by antecedent** [comment]
Many thanks to both of you! And yes, the detective work here is truly outstanding.
