### ISSUE TITLE
new-keyword-redefinable causes a Fatal error: Uncaught ReflectionException: Class "*" does not exist in

### ISSUE THREAD

**Issue by wvega** [antecedent/patchwork#126]
Hey everyone! Thank you so much for all your work on Patchwork. I use it for most of the tests I write, either through https://github.com/10up/wp_mock or using Patchwork's API directly.

Recently I started experimenting with the `new-keyword-redefinable` and ran into an issue. It seems that Patchwork is unable to resolve some namespaces correctly and as a result trying to run any test file fails with something like:

>Fatal error: Uncaught ReflectionException: Class "PHPUnit\TextUI\Timer" does not exist in vendor/antecedent/patchwork/src/CallRerouting.php:597

I was able to reproduce that particular error on a fresh project using Patchwork and PHPUnit only. You can follow these steps to give it a try:

1. Clone https://github.com/wvega/patchwork-namespace-resolution-issue
2. Run `composer install`
3. Run `vendor/bin/phpunit --bootstrap=tests/bootstrap.php tests`
4. You should see the error now

Then, if you change `new-keyword-redefinable` to `false` and run the `phpunit` command again, tests run normally.

The correct namespace for the `Timer` class is `SebastianBergmann\Timer\Timer`. `PHPUnit\TextUI` is the namespace of the `TestRunner` class, the one that instantiates a `Timer`.

I did some debugging and I think it all happens in the `resolveName()` function:

https://github.com/antecedent/patchwork/blob/36e656b26c7ce4e610e6f468f28a321eaa9306a2/src/CodeManipulation/Actions/Namespaces.php#L31

At that point I can see `SebastianBergmann\Timer\Timer` in the `$uses` array:

```
...
            [SebastianBergmann\Timer\Timer] => SebastianBergmann\Timer\Timer
...
```

However, the `resolveName()` function has no way to retrieve that value. Should the array have ` [Timer] => SebastianBergmann\Timer\Timer` instead?

If that's the case then maybe the problem is somewhere in `collectUseDeclarations()` but I didn't get to explore those functions.

I'm running PHP 8.1. Please let me know if I can provide any additional information.

**Comment by antecedent** [comment]
Thank you; it seems that you got to the root of the issue! This seems to be related to #120. Since that update, qualified names now come as single tokens, breaking the resolution mechanism that you described.

**Comment by antecedent** [comment]
Please try version 2.1.20, this should now be fixed in it.

**Comment by wvega** [comment]
@antecedent thank you for looking into this issue so quickly. 2.1.20 fixed the problem!
