### ISSUE TITLE
new-keyword-redefinable causes Parse error: syntax error, unexpected token "->"

### ISSUE THREAD

**Issue by wvega** [antecedent/patchwork#127]
Thank you again for quickly fixing #126! I ran into a different problem after I tried 2.1.20 on my project.

Patchwork rewrites the following:

```php
$test = new class(new TestClass()) {
};
```

as something like:

```
$test = new class\Patchwork\CallRerouting\getInstantiator(...)->instantiate() {
}
```

The `spliceAllInstantiations()` removes the parenthesis around `(new TestClass())` and produces an invalid anonymous class declaration:

https://github.com/antecedent/patchwork/blob/dbe712f7951cdadf4169e96adb5a89324ba43838/src/CodeManipulation/Actions/RedefinitionOfNew.php#L44-L46

I believe the fix for this problem is to add `T_CLASS` to the list of exceptions in `hasExtraParentheses()` so I'll try to pen a PR with tests and that oneliner.

**Comment by antecedent** [comment]
Thank you for fixing this! This is now part of version 2.1.21.
