### ISSUE TITLE
Looks like patchwork2.org was expired and is now gone.

### ISSUE THREAD

**Issue by aaronfc** [antecedent/patchwork#142]
Hey,
wanted to do some quick checks on the documentation and I couldn't reach [patchwork2.org/](http://patchwork2.org/).

Any possibility of recovering it? I tried archive but I can't seem to find much in there: https://web.archive.org/web/20230526073738/https://patchwork2.org/

**Comment by anomiex** [comment]
Looks like the domain expired and some expired domain squatter company grabbed it. @antecedent may have more info.

**Comment by antecedent** [comment]
Yes, this is exactly what happened. Sadly, I am yet to figure out how to reclaim the domain. It now seems to belong to 
Edomains LLC, but they still label the domain as "taken" when I search for it on their site, so I cannot really buy it back from them for the time being. 

Please access the site at https://antecedent.github.io/patchwork/. I will change the repository's metadata accordingly.
