### ISSUE TITLE
Could it be possible to patch a complete php file?

### ISSUE THREAD

**Issue by tomolimo** [antecedent/patchwork#22]
Hello,
First: thank you for your great (and marvelous) job!
Second: request explanations:
I would like to patch a complete PHP file, how is it possible to do so? Could it be included in next release?
Thank you,
Regards,
Tomolimo

**Comment by antecedent** [comment]
Hi,

Thank you :), but I'm unsure what was meant by _patching a complete PHP file_. Is it:

 * making PHP behave as if the file existed, while in reality it doesn't?
 * retrieving the code of a file after Patchwork has applied its transformations to it?
 * circumventing Patchwork's setup scheme that requires you to have at least two scripts?
 * something else?

**Comment by tomolimo** [comment]
Hello,
In fact I've got php files that are served by a web server, and I would like to patch these files.
i.e.: instead of file x.php I would like the web server to execute the patched version of it.

But the more I’m thinking to it the more I believe that Patchwork can’t do that, due to the fact that execution of Patchwork can’t precede the execution of the PHP script x.php… Or is there a way to tell the PHP interpreter that it should start executing Patchwork, before any other scripts?

Do you confirm ?

Thank you,
Regards,
Tomolimo

**Comment by ktomk** [comment]
the feedback is late, see [`auto_prepend_file` PHP ini setting](http://php.net/manual/en/ini.core.php#ini.auto-prepend-file) which you can use to setup patchwork before any php script.

**Comment by tomolimo** [comment]
Thank you anyway, I didn't know this PHP feature,
regards,
Tomolimo
