### ISSUE TITLE
A conflict occurs between Patchwork and wincache PHP module

### ISSUE THREAD

**Issue by tomolimo** [antecedent/patchwork#26]
Hello,
There is a conflict between Patchwork and wincache PHP module...
Thank you,
regards,
Tomolimo

**Comment by antecedent** [comment]
Hello, and many apologies for the horrible delay.
If the issue is still of any relevance, please check out the latest (untagged) commit. It might solve the problems with WinCache by perturbing timestamps and invoking `wincache_refresh_if_changed`.
