### ISSUE TITLE
Patchwork warning when included in PHPUnit bootstrap

### ISSUE THREAD

**Issue by cmounce** [antecedent/patchwork#38]
I have a PHPUnit bootstrap file that looks like this:

```php
<?php
require_once('./vendor/antecedent/patchwork/Patchwork.php');
require_once('./vendor/autoload.php');
// other stuff...
```

Patchwork is the first file included. But when I run "phpunit" from the command line, I get the message:

> PHP Warning:  Please import Patchwork from a point in your code where no user-defined function, class or trait is yet defined. composer\autoload\includefile() and possibly others currently violate this. in /home/cmounce/Documents/patchwork-phpunit/vendor/antecedent/patchwork/Patchwork.php on line 93

This is happening with Patchwork 1.4.1. Both PHPUnit and Patchwork are Composer dependencies of the project:

```json
{
    "require-dev": {
        "phpunit/phpunit": "^4.8",
        "antecedent/patchwork": "1.4.1"
    }
}
```

**Comment by bswatson** [comment]
Running into this same problem as well. Switched back to 1.4 until this is cleared up.

**Comment by antecedent** [comment]
I apologize for still not having documented this, but this can be remedied by creating a `patchwork.json` with the following contents:

```json
{
    "suppress-warnings": [
        "composer*"
    ]
}
```

Version 1.4.2, which is now live, simply includes this setting by default.

**Comment by cmounce** [comment]
Awesome! Thanks for the fast turnaround time in fixing this issue!

**Comment by ericmann** [comment]
Hmm ... I added the `patchwork.json` file with those contents and, using 1.4.2, still see the warnings repeatedly. This breaks headless execution via tools like Travis and I _still_ have to roll back to 1.4.0 to get things to work right. Any other thoughts?

**Comment by antecedent** [comment]
@ericmann: for a quick fix, you can always take the `{"suppress-warnings": ["*"]}` route. However, Patchwork is probably having problems with a _different_ method/function here; its name should show up in the warnings. If it's one that's a part of an usual testing setup, please make a pull request to include it in the _default_ `patchwork.json`.
