### ISSUE TITLE
Warning on stream_wrapper_restore

### ISSUE THREAD

**Issue by Purus** [antecedent/patchwork#48]
I am getting the below warning in my shared hosting. But there was no warning in my local WAMPP setup.

Is this anything related to server?

```
Message:	stream_wrapper_restore(): phar:// never existed, nothing to restore
File:	/home/iyaffxpe/public_html/classes/vendor/antecedent/patchwork/src/CodeManipulation/Stream.php
Line:	35
```

**Comment by antecedent** [comment]
Which version of PHP is that?

**Comment by Purus** [comment]
I am using PHP 5.7.26

**Comment by antecedent** [comment]
This seems like Suhosin, could you verify that it is enabled? I will attempt a patch meanwhile.

**Comment by Purus** [comment]
Sorry. I could not find anything related to "suhosin" in my php.ini file.

Where else I should be checking?

Thanks,
R.Purusothaman

**Comment by antecedent** [comment]
Maybe it's something else then. Please try the last push to `master`. This is just suppressing the warning though.

**Comment by Purus** [comment]
Thanks for the fix.
