### ISSUE TITLE
$frame is undefined in CallRerouting::connectDefaultInternals

### ISSUE THREAD

**Issue by maartenscholz** [antecedent/patchwork#50]
When mocking an class with Prophecy which has a `@link` annotation (which are read by phpdocumenter which does a `call_user_func_array` which patchwork intercepts) It gets into a path in patchwork which passes through `CallRerouting::connectDefaultInternals`. In `connectDefaultInternals` there is a `$frame` variable which is never set. This causes my test to fail  `Undefined variable: frame`. I would fix it myself but I don't have enough knowledge of the internals of patchwork.

Using version `2.0.1`

**Comment by antecedent** [comment]
Does version 2.0.2 solve the issue?

**Comment by maartenscholz** [comment]
The frame error is gone but now I'm getting `Undefined index: class`

**Comment by antecedent** [comment]
I'm sorry; this is taking longer to fix than I had expected. I'll still try to have it ready by tonight, though.

**Comment by maartenscholz** [comment]
No worries, thanks for already looking into it!

**Comment by antecedent** [comment]
Could you check if the latest commit to `master` fixes this?

**Comment by maartenscholz** [comment]
When using `master` test are passing!

**Comment by antecedent** [comment]
Glad to hear that :) I've tagged it as 2.0.3 now.

**Comment by maartenscholz** [comment]
We are back on `2.0.3` and everything is working fine. Thanks a lot for the quick response/fix!
