### ISSUE TITLE
Internal function calls that use the splat operator turn into syntax errors

### ISSUE THREAD

**Issue by antecedent** [antecedent/patchwork#56]
As in `array_map($callback, ...$arrays)` &rarr; `\Patchwork\CallRerouting\dispatchDynamic('array_map', [$callback, ...$arrays])`.

**Comment by ktomk** [comment]
Just an idea which might be already in your mind: 

`array_map($callback, ...$arrays)` → 
`\Patchwork\CallRerouting\dispatchDynamic('array_map', \Patchwork\CallRerouting\dispatchDynamicArgs($callback, ...$arrays))`

~~~
function dispatchDynamicArgs(...$args) {
    return $args;
}

~~~
