### ISSUE TITLE
Minimal use case not operable

### ISSUE THREAD

**Issue by jhabdas** [antecedent/patchwork#59]
Given the following `patchwork.json`:

```json
{"redefinable-internals": ["die"]}
```

And the following `composer.json`:

```json
{
  "autoload": {
    "files": [
      "src/hyperdrive.php"
    ]
  },
  "autoload-dev": {
    "files": [
      "vendor/antecedent/patchwork/Patchwork.php"
    ]
  },
  "require-dev": {
    "kahlan/kahlan": "^3.1",
    "antecedent/patchwork": "^2.0"
  }
}
```

Where `hyperdrive.php` contains:

```php
namespace hyperdrive;

die( 'Now you are going to die! BAM!' );

function enter_hyperspace( $dark_energy ) {
  echo "<script>{$dark_energy}</script>";
}
```

And `hyperdrive.spec.php` contains (notice the `redefine` here):

```php
namespace hyperdrive\spec;

use function Patchwork\redefine as redefine;
use function Patchwork\always as always;

use function hyperdrive\enter_hyperspace;

redefine('die', always(null));

describe('hyperdrive', function () {
  describe('enter_hyperspace()', function () {
    it('echos empty script given empty string', function () {
      $closure = function() { enter_hyperspace(''); };
      expect($closure)->toEcho('<script></script>');
    });
  });
});
```

Running `vendor/bin/kahlan` results in:

<samp>Now you are going to die! BAM!%</samp>

Whereas I would expect `patchwork` to _redefine_ `die` and allow execution to continue.

**Comment by antecedent** [comment]
This seems trivial to add to the implementation, so it should be live by tomorrow. The explanation for why it's not there yet is that `die()` is a "language construct" and not a regular function, so it has a dedicated parser token and doesn't generate normal responses to `function_exists()` etc.

**Comment by jhabdas** [comment]
Solid.

**Comment by antecedent** [comment]
Please try version 2.0.5 for this.

**Comment by jhabdas** [comment]
Great. Will report back in just a few hours. Really looking forward to blanketing my codebase with tests. If any more changes are needed I can always test using a branch or commit SHA if that helps your workflow and eases ChangeLogs

**Comment by jhabdas** [comment]
Works on my machine. Thanks!
