### ISSUE TITLE
unexpected '$__pwClosureName' (T_VARIABLE), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by moraleida** [antecedent/patchwork#63]
Running PHP 7.0.18 (cli) on Docker.

Apparently this is the same as #16 , happening on all versions since at least 2.0. I get this error message:
                                                                                             

>   [Codeception\Exception\TestParseException]                                                      
>   Couldn't parse test '/var/www/path/to/Test.php'  
>   syntax error, unexpected '$__pwClosureName' (T_VARIABLE), expecting identifier (T_STRING) 

Not sure if I'm doing something wrong:

```
<?php

use function Patchwork\{redefine, always};

class PostType_Test extends \Codeception\Test\Unit {

	protected $tester;

	protected function _before() {
	}

	protected function _after() {
	}

	public function test_resource() {
		redefine( 'get_option', always(null) );
		$option = get_option( 'bloginfo' );
                $this->assertNotEmpty($option);
	}
}
```

**Comment by antecedent** [comment]
It's very likely the `use function` with the curly brackets. Patchwork is probably mistaking it for a function definition. Try using
```php
use function Patchwork\redefine, Patchwork\always;
```
to test the hypothesis.

**Comment by moraleida** [comment]
That didn't work either, but ditching the `use` statement and using them as `Patchwork\redefine()` and `Patchwork\always()` did. 

Go figure.

**Comment by antecedent** [comment]
Should now be fixed.
