### ISSUE TITLE
Latest doctrine/instantiator bugs out with patchwork

### ISSUE THREAD

**Issue by krodyrobi** [antecedent/patchwork#64]
### Versions

Dependency | Version
------- | --------
PHPUnit | 5.7.* and 6.2.*
Doctrine/instantiator |  1.1.0
PHP | 5.6 and 7.1
Patchwork | ^2.0

### MCV example

https://github.com/krodyrobi/patchwork-doctrine

### Temporary workaround

Add `"doctrine/instantiator": "1.0.x-dev"` to `composer.json`

**Comment by krodyrobi** [comment]
Cross-linking https://github.com/sebastianbergmann/phpunit/issues/2746

**Comment by tfrommen** [comment]
Hey there,

thanks for _fixing_ this. But ... it's not working for me.

I have a repository that depends on Patchwork and PHPUnit 5.7, and thus Instantiator (which I get as version 1.1.0).

Still the fatal error keeps on coming. Any idea why that is?

**Comment by krodyrobi** [comment]
In your composer.json replace to `"antecedent/patchwork": "^2.0"`, and issue a `composer update`

**Comment by tfrommen** [comment]
I **am** using 2.0.8.

**Comment by antecedent** [comment]
Also, if there's a `cache-path` in `patchwork.json`, please manually clear the folder it refers to.

**Comment by tfrommen** [comment]
Thanks for the info. However, I don't use any `patchwork.json` ( I'm not redefining core stuff such as `exit`), and the `cache/` **folder** is also not present.

**Comment by antecedent** [comment]
Please use `{"blacklist": "/path/to/Instantiator.php"}` for now. I apologize for any inconvenience caused by this bug, and will investigate it further later today.

**Comment by tfrommen** [comment]
No problem, and thanks!
For now, I just fix Instantiator to `v1.0.5` where I doesn't have the `void` return type hint, so no fatal error.

**Comment by Rarst** [comment]
Also having issues with 2.0.8, any failing test or anything produces the fatal error in Instantiator.

Not doing anything with Patchwork directly, using it via [Brain Monkey](https://github.com/Brain-WP/BrainMonkey). Downgrading to Instantiator 1.0.5 seems to help for now.

cc @gmazzap

**Comment by antecedent** [comment]
This time, I have successfully reproduced the bug with an actual copy of doctrine/instantiator 1.1, and made a second attempt at the fix.

**Comment by Rarst** [comment]
Seems to have gotten my issue this time! No errors with 2.0.9 and Instantiator 1.1 so far, thaaank you. :)

**Comment by tfrommen** [comment]
Wow, nice one, @antecedent! Thanks!
Damn `use`-ing closures, right? 😀

**Comment by krodyrobi** [comment]
Yep it seems to have solved the issue completely. Thank you!
