### ISSUE TITLE
Redefine "new" instance in code

### ISSUE THREAD

**Issue by mieszkomalawski** [antecedent/patchwork#66]
Hi

It would be great to be able to replace "new" instance of some class. Eg.

// tested method
public testedMethod(){
    // do something 
   $instance = new SomeLegacyClassThatDoesThingsInConstructor();
 // do more work
}

then:

redefine('new SomeLegacyClassThatDoesThingsInConstructor'){
   return TestStub();
}

**Comment by antecedent** [comment]
This is a work-in-progress on the `redefinition-of-new` branch. A preliminary implementation is already available.
