### ISSUE TITLE
2.1.0 syntax error, unexpected 'static'

### ISSUE THREAD

**Issue by mieszkomalawski** [antecedent/patchwork#68]
Problem exists only in 2.1.0:

new static($args)

couses error:

syntax error, unexpected 'static' (T_STATIC)

**Comment by antecedent** [comment]
Please try version 2.1.2.

**Comment by jrfnl** [comment]
I have a feeling this issue should be (long) closed ?

**Comment by anomiex** [comment]
Presumably so.
