### ISSUE TITLE
Call to a member function load() on null

### ISSUE THREAD

**Issue by fede91it** [antecedent/patchwork#72]
Hello,

I imported Patchwork in this way

```php
require_once __DIR__ . '/vendor/antecedent/patchwork/Patchwork.php';
```

And I get the error `Call to a member function load() on null` in vendor\antecedent\patchwork\src\CallRerouting.php:529

What is wrong?

This is happen when I move from 2.0.9 to 2.1.0

**Comment by antecedent** [comment]
Please try version 2.1.5.
If the problem persists, I'll probably need some more context, like a complete stack trace.

**Comment by fede91it** [comment]
It works wonderfully! ✨

You're doing an excellent job, my compliments really!
