### ISSUE TITLE
time example of Patchwork homepage not working

### ISSUE THREAD

**Issue by maiermic** [antecedent/patchwork#78]
I installed `antecedent/patchwork` version `2.1.7` using composer.

**patchwork.json**

```js
{
  "redefinable-internals": [
    "time"
  ]
}
```

**example.php**

```php
<?php
require_once dirname(__FILE__) . '/../lib/vendor/antecedent/patchwork/Patchwork.php';
\Patchwork\redefine('time', \Patchwork\always(strtotime('Dec 31, 1999')));
echo date('Y-m-d', time()); # current date, but expected is: 1999-12-31
```

Redefinition of `time` does not work. It still returns the current date.

---

PHP 5.5.9-1ubuntu4.14

**Comment by antecedent** [comment]
Once you include Patchwork, its functionality will only become available in files that are included next. As a result, the following will work:

**patchwork.json** (not package.json, but this was probably a typo)
```json
{
  "redefinable-internals": [
    "time"
  ]
}
```
**index.php**
```php
```

**Comment by maiermic** [comment]
Thanks for the quick answer 👍
