### ISSUE TITLE
Patchwork breaks support for PHP7 strict types declarations

### ISSUE THREAD

**Issue by armills** [antecedent/patchwork#79]
## Description
It seems that Patchwork is interfering with the [PHP7 strict types declaration](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict). When I try to run a test that includes this declaration, I get the following error when Patchwork is included:
```
Fatal error: strict_types declaration must be the very first statement in the script in /var/www/app/library/Source.php on line 2
```

Is this a known problem, or are there any workarounds for this?

**Comment by antecedent** [comment]
Please retest with the current `master`.

**Comment by armills** [comment]
Thanks so much for the quick turnaround! 🙇🙇🙇 This seems to have solved it!
