### ISSUE TITLE
Recursion on Grouped Use Statements

### ISSUE THREAD

**Issue by jeremeamia** [antecedent/patchwork#86]
Hello, we are using Patchwork in our testsuite, and after we updated to PHP 7, we started updating our dependencies. There is a package that uses grouped use statements, and a test importing that class is failing because Patchwork is blowing up with

> Error: Maximum function nesting level of '256' reached, aborting!

On this line of code: https://github.com/antecedent/patchwork/blob/master/src/CodeManipulation/Actions/Namespaces.php#L138

I *think* it's because (since this is a recursive call) that `$pos` is never incremented (since that happens at the bottom of `parseUseDeclaration` which is not reached), and so the recursive call is being made without any state change, causing it to do the same thing over and over.

**Comment by jeremeamia** [comment]
If the code was changed to
```php
parseUseDeclaration($s, $pos + 1, $aliases, $prefix . '\\', $type);
```
Then that might work. It seems to, anyway, with my testsuite.

**Comment by antecedent** [comment]
Hello and thank you for the report!

I tried pasting a couple examples from [the grouped `use` RFC](https://wiki.php.net/rfc/group_use_declarations) into a test case. Strangely enough, nothing interesting happened.

So I haven't been able to reproduce the issue for now :/

What I suspect, though, is that there's actually no infinite recursion here, and that it just needs more stack frames to bottom out. Could you set `xdebug.max_nesting_level` to a higher value and see what happens? (PHP itself puts no limits on nesting per se.)

Also, I reread the version of that particular line that you suggest in comment 2 &ndash; reread it multiple times. Perhaps it's just me, but it seems to read identically to what `master` (and `2.1.8`) already has. 

Did you mean to paste something else?

**Comment by jeremeamia** [comment]
Thanks for the response! Well, as it turns out, my `composer update` did not update as far as I thought, and I have an old version. Looks like you already [fixed my bug here](https://github.com/antecedent/patchwork/commit/97ec552cd688d37b699e1ae600ab131968395f2e#diff-4b88bb82df94a8d15675c03fc668203aR141). That explains why my suggestion seemed pointless. 😅

**Comment by jeremeamia** [comment]
Thanks for taking a look though. :-)
