### ISSUE TITLE
Bug - New line needed after start php tag. Fatal error Call to undefined function Patchwork\Redefinitions\LanguageConstructs\_\Patchwork\CallRerouting\deployQueue()

### ISSUE THREAD

**Issue by juancarmo** [antecedent/patchwork#94]
I really tried to work this issue out by myself, but I could not get a deep understanding of how patchwork works, that is why I leave this piece of code that perfectly reproduces what I believe is a BUG in the package.

**Always add a new line after the <?php start tag** otherwise, this can happen.

Example:
_index.php_
```
<?php

require __DIR__ . '/vendor/antecedent/patchwork/Patchwork.php';
require __DIR__ . '/profiler.php';

echo PHP_EOL;
testfunction();
echo PHP_EOL;
```

profiler.php_
```
<?php
include_once("./includeme.php");

Patchwork\redefine("time", function () {
    return strtotime("Dec 31, 1999");
});

echo date("Y-m-d", time());
```

_patchwork.json_
```
{
    "redefinable-internals": [
        "time",
        "include_once"
    ]
}
```

Whenever you execute this piece of code you will get the following error:
**PHP Fatal error:  Uncaught Error: Call to undefined function Patchwork\Redefinitions\LanguageConstructs\_\Patchwork\CallRerouting\deployQueue() in /home/jcm/personal/patchwork-test1/profiler.php:2**

Now ... the workaround for this issue is to just **add a new line** right after the <?php tag in file profiler.php like this:

profiler.php_
```
<?php
// <------------------NEW LINE HERE
include_once("./includeme.php");

Patchwork\redefine("time", function () {
    return strtotime("Dec 31, 1999");
});

echo date("Y-m-d", time());
```

Now everything works as expected.

Documentation for this package is really needed, I would help, but I dont understand the entry execution point of Patchwork.

I hope to get some cmments regarding this issue.

Thanks. (@antecedent ) for the great work.

**Comment by antecedent** [comment]
My apologies for such a delay. Should now be fixed in 2.1.11.

Also, point taken: I will make an effort to document the internals. Now that my capacity to respond readily to Patchwork's incidents is rather limited, I see that it's especially relevant.
