### ISSUE TITLE
Redefine does not work for void static methods

### ISSUE THREAD

**Issue by Mariyo** [antecedent/patchwork#95]
Hello, 

I have issue, that `redefine` does not work for static methods with `:void` return type in signature:

```php
<?php

use function Patchwork\redefine;
use function Patchwork\restoreAll;

class MyPatchworkTest extends TestCase
{
    public function tearDown()
    {
        restoreAll();
    }

    public static function staticVoidMethod(): void
    {
        echo 'This should be omitted';
    }

    public function testPatchwork(): void
    {
        $callingCount = 0;

        redefine([__CLASS__, 'staticVoidMethod'], static function () use (&$callingCount) {
            $callingCount++;
        });

        self::staticVoidMethod();

        static::assertSame($callingCount, 1);
    }
}
```

Result of test is **Failed asserting that 1 is identical to 0**.

Patchwork version is **2.1.8**

**Comment by ethanlu** [comment]
In the test, you need to call staticVoidMethod once before the assert so $callingCount can increment to 1.

**Comment by antecedent** [comment]
This is indeed a bug; I'll be working on it today. Many thanks for the report!

**Comment by antecedent** [comment]
Please try version 2.1.10; I hope it fixes that.

**Comment by Mariyo** [comment]
Big thx for so fast fix!

**Comment by Mariyo** [comment]
Hello, could you publish the latest version on packagist? I've received the problem of missing version:

![image](https://user-images.githubusercontent.com/1678254/67656809-2f24fb80-f955-11e9-9a95-a8614172dcb9.png)

Thank you a lot!

**Comment by antecedent** [comment]
I just did; please retry.

**Comment by Mariyo** [comment]
Everything fixed now, thank you. :+1:
